# Generated by Django 4.2 on 2024-07-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='email',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
