# Generated by Django 4.2 on 2024-07-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.TextField(max_length=100)),
                ('phone', models.TextField(db_index=True, max_length=15)),
                ('email', models.TextField(db_index=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
