# Generated by Django 4.2 on 2024-07-13 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('interview_date', models.DateField(db_index=True)),
                ('interview_start_time', models.TimeField()),
                ('interview_end_time', models.TimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='candidate.candidateinfo')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recruiter.recruiterinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecruiterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('day', models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recruiter.recruiterinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
